scikit-learn User Guide
http://scikit-learn.org/stable/user_guide.html
http://scikit-learn.org/stable/modules/classes.html

# Supervised Learning

Acknowledgement: some materials used here are from DataCamp's sklearn tutorial.

Supervised learning by iris data. This data sets consists of 3 different types of irises' (Setosa, Versicolour, and Virginica) petal and sepal length, stored in a 150x4 numpy.ndarray. The rows being the samples and the columns being: Sepal Length, Sepal Width, Petal Length and Petal Width.

**Iris Data
Sepal length| Sepal width| Petal length| Petal width|    Species
        5.1	     3.5	   1.4	          0.2	          setosa
        4.9	     3.0	   1.4 	          0.2     	      setosa
        4.7	     3.2	   1.3            0.2     	      setosa
        4.6	     3.1	   1.5	          0.2 	          setosa

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')

from sklearn import datasets

In [ ]:
iris = datasets.load_iris()

We would like to know what are iris data. We would first find out its type by function type().

In [ ]:
type(iris)

Bunch is a dictionary that supports attribute-style access, which means bunch lets you use a Python dict like it's an Object. Now we can check what elements are in the data set.

In [111]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [ ]:
iris.target_names   #access iris data like an Object

In [ ]:
iris.DESCR

In [ ]:
iris['target'] # another way to access iris data like a dictionary

In [ ]:
iris['data']

In [ ]:
iris.data.shape

In [ ]:
type(iris.data)

**Exploratory data analysis

In [ ]:
X=iris.data
y=iris.target

DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object. 

In [ ]:
df = pd.DataFrame(X,columns=iris.feature_names)

In [ ]:
print(iris.feature_names)

In [ ]:
print(df.head())

Visual exploratory data analysis

In [ ]:
_fig = pd.plotting.scatter_matrix(df,c=y,figsize = [8,8],s=150,marker='D')

In [ ]:
plt.show()

k-NN classification
============================

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
# Create a k-NN classifier with 6 neighbors
knn = KNeighborsClassifier(n_neighbors=6)

# Fit the classifier to the data
#the features and targets are numpy arrays
knn.fit(iris['data'], iris['target']) 
KNeighborsClassifier(algorithm='auto', leaf_size=30,metric='minkowski',
                     metric_params=None, n_jobs=1,n_neighbors=6, p=2,weights='uniform')
                    

In [ ]:
iris['data'].shape

In [ ]:
iris['target'].shape

Now let us predict unlabled data

In [ ]:
prediction = knn.predict(X_new) #X_new is not defined

**Exercise 1:
Create X_new to finish the prediction. Make sure the scikit-learn API will accept X_new as long as they are of the right shape.

Measuring model performance
============================

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=21, stratify=y)

In [83]:
knn = KNeighborsClassifier(n_neighbors=8)

In [84]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=8, p=2,
           weights='uniform')

In [85]:
y_pred = knn.predict(X_test)

In [86]:
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [2 1 2 2 1 0 1 0 0 1 0 2 0 2 2 0 0 0 1 0 2 2 2 0 1 1 1 0 0 1 2 2 0 0 1 2 2
 1 1 2 1 1 0 2 1]


In [87]:
knn.score(X_test, y_test)

0.9555555555555556

**Exercise 2:

Data set
The MNIST digits recognition dataset has 10 classes, the digits 0 through 9. A reduced version of the MNIST dataset is one of scikit-learn's included datasets, and that is the one we will use in this exercise.
Each sample in this scikit-learn dataset is an 8x8 image representing a handwritten digit. Each pixel is represented by an integer in the range 0 to 16, indicating varying levels of black. 

Instructions
*Import datasets from sklearn and matplotlib.pyplot as plt.
*Load the digits dataset using the .load_digits() method on datasets.
*Print the keys and DESCR of digits.
*Print the shape of images and data keys using the . notation.
*Display the 1010th image using plt.imshow(). This has been done for you.

In [ ]:
# Import necessary modules
from sklearn import datasets
import matplotlib.pyplot as plt

# Load the digits dataset: digits
digits =

# Print the keys and DESCR of the dataset
print(____)
print(____)

# Print the shape of the images and data keys
print(____.____.shape)
print(____.____.shape)

# Display digit 1010
plt.imshow(digits.images[1010], cmap=plt.cm.gray_r, interpolation='nearest')
plt.show()

**Answer of the exercise 2:

In [ ]:
# Import necessary modules
from sklearn import datasets
import matplotlib.pyplot as plt

# Load the digits dataset: digits
digits = datasets.load_digits()

# Print the keys and DESCR of the dataset
print(digits.keys())
print(digits.DESCR)

# Print the shape of the images and data keys
print(digits.images.shape)
print(digits.data.shape)

# Display digit 1010
plt.imshow(digits.images[1010], cmap=plt.cm.gray_r, interpolation='nearest')
plt.show()

In [102]:
print(digits.keys())

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])


In [110]:
print(digits.images[3])

[[  0.   0.   7.  15.  13.   1.   0.   0.]
 [  0.   8.  13.   6.  15.   4.   0.   0.]
 [  0.   2.   1.  13.  13.   0.   0.   0.]
 [  0.   0.   2.  15.  11.   1.   0.   0.]
 [  0.   0.   0.   1.  12.  12.   1.   0.]
 [  0.   0.   0.   0.   1.  10.   8.   0.]
 [  0.   0.   8.   4.   5.  14.   9.   0.]
 [  0.   0.   7.  13.  13.   9.   0.   0.]]


In [112]:
print(digits.data[3])

[  0.   0.   7.  15.  13.   1.   0.   0.   0.   8.  13.   6.  15.   4.   0.
   0.   0.   2.   1.  13.  13.   0.   0.   0.   0.   0.   2.  15.  11.   1.
   0.   0.   0.   0.   0.   1.  12.  12.   1.   0.   0.   0.   0.   0.   1.
  10.   8.   0.   0.   0.   8.   4.   5.  14.   9.   0.   0.   0.   7.  13.
  13.   9.   0.   0.]


In [113]:
print(digits.images.shape)

(1797, 8, 8)


In [114]:
print(digits.data.shape)

(1797, 64)


**Exercise 3:

Train/Test Split + Fit/Predict/Accuracy

After creating arrays for the features and target variable, you will split them into training and test sets, fit a k-NN classifier to the training data, and then compute its accuracy using the .score() method.

Instructions
*Import KNeighborsClassifier from sklearn.neighbors and train_test_split from sklearn.model_selection.
*Create an array for the features using digits.data and an array for the target using digits.target.
*Create stratified training and test sets using 0.25 for the size of the test set. Use a random state of 30. Stratify the split according to the labels so that they are distributed in the training and test sets as they are in the original dataset.
*Create a k-NN classifier with 7 neighbors and fit it to the training data.
*Compute and print the accuracy of the classifier's predictions using the .score() method.

In [ ]:
# Import necessary modules
____
____

# Create feature and target arrays
X = ____
y = ____

# Split into training and test set
X_train, X_test, y_train, y_test = ____(____, ____, test_size = ____, random_state=____, stratify=____)

# Create a k-NN classifier with 7 neighbors: knn
knn = ____

# Fit the classifier to the training data
____

# Print the accuracy
print(knn.score(____, ____))


**Answer of the exercise 3:

In [115]:
# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Create feature and target arrays
X = digits.data
y = digits.target

# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=30, stratify=y)

# Create a k-NN classifier with 7 neighbors: knn
knn = KNeighborsClassifier(n_neighbors=7)

# Fit the classifier to the training data
knn.fit(X_train,y_train)

# Print the accuracy
print(knn.score(X_test, y_test))

0.984444444444


**Exercise 4:

By observing how the accuracy scores differ for the training and testing sets with different values of k, you will develop your intuition for overfitting and underfitting.

The training and testing sets are available to you in the workspace as X_train, X_test, y_train, y_test. In addition, KNeighborsClassifier has been imported from sklearn.neighbors.

Instructions:
*Inside the for loop:
Setup a k-NN classifier with the number of neighbors equal to k.
Fit the classifier with k neighbors to the training data.
Compute accuracy scores the training set and test set separately using the .score() method and assign the results to the train_accuracy and test_accuracy arrays respectively.



In [ ]:
# Setup arrays to store train and test accuracies
neighbors = np.arange(1, 9)
train_accuracy = np.empty(len(neighbors))
test_accuracy = np.empty(len(neighbors))

# Loop over different values of k
for i, k in enumerate(neighbors):
    # Setup a k-NN Classifier with k neighbors: knn
    knn = ____

    # Fit the classifier to the training data
    ____
    
    #Compute accuracy on the training set
    train_accuracy[i] = knn.score(____, ____)

    #Compute accuracy on the testing set
    test_accuracy[i] = ____(____, ____)

# Generate plot
plt.title('k-NN: Varying Number of Neighbors')
plt.plot(neighbors, test_accuracy, label = 'Testing Accuracy')
plt.plot(neighbors, train_accuracy, label = 'Training Accuracy')
plt.legend()
plt.xlabel('Number of Neighbors')
plt.ylabel('Accuracy')
plt.show()

**Answer of the exercise 4:

In [ ]:
# Setup arrays to store train and test accuracies
neighbors = np.arange(1, 9)
train_accuracy = np.empty(len(neighbors))
test_accuracy = np.empty(len(neighbors))

# Loop over different values of k
for i, k in enumerate(neighbors):
    # Setup a k-NN Classifier with k neighbors: knn
    knn = KNeighborsClassifier(n_neighbors=k)

    # Fit the classifier to the training data
    knn.fit(X_train,y_train)
    
    #Compute accuracy on the training set
    train_accuracy[i] = knn.score(X_train, y_train)

    #Compute accuracy on the testing set
    test_accuracy[i] = knn.score(X_test, y_test)

# Generate plot
plt.title('k-NN: Varying Number of Neighbors')
plt.plot(neighbors, test_accuracy, label = 'Testing Accuracy')
plt.plot(neighbors, train_accuracy, label = 'Training Accuracy')
plt.legend()
plt.xlabel('Number of Neighbors')
plt.ylabel('Accuracy')
plt.show()